title:              Machine Learning Notes
email:              aademola@aimsammi.org
description:        A page for all notes regarding machine learning work
author:             Ademola Abiodun Saheed
baseurl:            ""
url:                "https://Eminent01.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    Eminent01
facebook_username:  
instagram_username:  
linkedin_username: abiodun-ademola  

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
